version: '3.8'
services:
  app:
    container_name: app.sysdocz
    build: app
    ports:
      - "8080:80"
      - "8053:53"
    environment:
      - ENVIRONMENT=development
    volumes:
      - sysdocz_app:/etc/bind
      - backup:/backup
    # env_file:
    #   - app/.env

  database:
    container_name: database.sysdocz
    build: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    env_file:
      - database/.env
    ports:
      - "5432:5432"
    networks:
      - sysdocz
    volumes:
      - sysdocz_database:/var/lib/postgresql/data

networks:
  sysdocz:
    external: true

volumes:
  sysdocz_app:
  sysdocz_database:
  backup:

  



